### ISSUE TITLE
Something is going wrong. Same error with ytfzf

### ISSUE THREAD

**Issue by lordofwizard** [pystardust/quotes#1]
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div#taw > div > p > a:first-of-type text{}'.
Usage: pup [OPTIONS] COMMAND [ARGS]...
Try 'pup --help' for help.

Error: No such command 'div[data-mh="-1"] i text{}'.
No quotes found.
lordofwizard@pop-os:~/Documents/gits/quotes$

**Comment by pystardust** [comment]
What version of pup are you using?
This command seems to be only in the newer versions of pup.
For `ytfzf` I have removed pup altogether

**Comment by lordofwizard** [comment]
```
lordofwizard@pop-os:~$ pup --version
pup, version 1.0.0a9
lordofwizard@pop-os:~$ ^C
```

# INGORE THE HOSTNAME

**Comment by pystardust** [comment]
That version number seems odd
```sh
pup --version                                                      17:18
0.4.0
```
I have installed pup as per the it's [github page](https://github.com/EricChiang/pup)
Try installing the latest version as mentioned in the docs of pup
```
go get github.com/ericchiang/pup
```

Also you need to add the go path to your path. This command will install pup into `~/go/bin/` or if changed  then to `$GOPATH`. Add that to your path or copy `pup` into your path.
